# Generated by Django 5.2.7 on 2026-05-11 11:48

from django.db import migrations, models


def convert_shipped_orders_to_paid(apps, schema_editor):
    Order = apps.get_model('store', 'Order')
    Order.objects.filter(status='shipped').update(status='paid')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_skill_level'),
    ]

    operations = [
        migrations.RunPython(convert_shipped_orders_to_paid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('paid', 'Оплачено'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
