# Generated by Django 5.2.7 on 2026-04-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_products',
            field=models.TextField(blank=True, null=True),
        ),
    ]
